name: Waka Readme

on:
  schedule:
    - cron: '0 15 * * *'
  issue_comment:
    types: [created, ]

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS : True
          SHOW_COMMIT : True
          SHOW_DAYS_OF_WEEK : False
          SHOW_LANGUAGE : True
          SHOW_OS : True
          SHOW_PROJECTS : True
          SHOW_TIMEZONE : True
          SHOW_EDITORS : True
          SHOW_LANGUAGE_PER_REPO : False
          SHOW_SHORT_INFO : False
          SHOW_LOC_CHART : False
